/**
 * Conquest (Kuşatma) — static challenge bank.
 *
 * Hand-authored, semantically classified geography / world-culture questions
 * across three input shapes: quiz (multiple-choice), type_race (free-text
 * "write a country"), and flag_guess (flag → country).
 *
 * Design goals (content revision 2026-06):
 *   • Players should not only drill country↔capital and flag↔country recall.
 *     The bank is dominated by physical geography, country location/features,
 *     famous landmarks & world heritage, world records (with an explicit,
 *     undisputed metric), and history-linked geography.
 *   • Capital questions (both directions) and direct flag→country questions are
 *     intentionally a minority — see scripts/check-conquest-question-content.ts,
 *     which fails the build if either rises above its cap.
 *   • Every quiz / type_race / flag entry carries an explicit `family` and
 *     `difficulty`.  The planner reads these directly instead of guessing a
 *     family from the entry id (no id-range heuristics), so adding a question
 *     is a self-classifying, one-line change.
 *
 * Each entry has a stable `id` used by the anti-repetition tracker in
 * conquestGameplay.ts / conquestQuestionPlanner.ts so the same question never
 * appears twice in a match while the bank has unused entries.
 *
 * Runtime answer comparison goes through `conquestChallengeValidation` which
 * handles trimming, casing, and Turkish diacritic tolerance.  For multiple
 * choice entries the correct answer (`acceptedAnswers[0]`) is always one of the
 * `choices` — verified by scripts/check-conquest-quiz-shuffle.ts.
 *
 * No React, no Supabase — pure data.  Pickers are called only by the host
 * client; the selected challenge is stored in gameplay_state so every other
 * client renders the same payload.
 */

import type {
  ConquestQuestionFamily,
  ConquestQuestionDifficulty,
} from "./types";

/** Multiple-choice families that a hand-authored quiz entry may carry.  The
 *  two generated MC families (`capital_to_country_mc`, `flag_to_country_mc`)
 *  are minted by the planner, never authored here. */
export type ConquestQuizFamily = Extract<
  ConquestQuestionFamily,
  | "country_to_capital_mc"
  | "flag_symbol_mc"
  | "neighbor_mc"
  | "physical_geo_mc"
  | "region_mc"
  | "landmark_mc"
  | "world_record_mc"
  | "history_geo_mc"
>;

/** Free-text families that a type_race entry may carry. */
export type ConquestWriteFamily = Extract<
  ConquestQuestionFamily,
  "country_starts_with_letter" | "country_by_criteria"
>;

// ─────────────────────────────────────────────────────────────────────────────
// Quiz — short geography / world-culture Q&A, multiple choice
// ─────────────────────────────────────────────────────────────────────────────

export interface QuizBankEntry {
  id:               string;
  prompt:           string;
  /** UI renders choice buttons.  The correct answer must be one of these. */
  choices:          string[];
  /** All forms that should validate as correct.  Case / diacritic insensitive.
   *  `acceptedAnswers[0]` is the canonical option present in `choices`. */
  acceptedAnswers:  string[];
  /** Semantic question shape — drives the planner's family anti-repetition. */
  family:           ConquestQuizFamily;
  /** Content difficulty — audited by the content-balance check. */
  difficulty:       ConquestQuestionDifficulty;
}

export const CONQUEST_QUIZ_BANK: QuizBankEntry[] = [
  // ── country → capital (minority: kept small & iconic) ────────────────────
  { id: "q01", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "Türkiye'nin başkenti hangi şehirdir?",
    choices: ["Ankara", "İstanbul", "İzmir", "Bursa"],
    acceptedAnswers: ["Ankara"] },
  { id: "q02", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "Fransa'nın başkenti neresidir?",
    choices: ["Paris", "Lyon", "Marsilya", "Nice"],
    acceptedAnswers: ["Paris"] },
  { id: "q03", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "Japonya'nın başkenti neresidir?",
    choices: ["Tokyo", "Osaka", "Kyoto", "Seul"],
    acceptedAnswers: ["Tokyo", "Tokio"] },
  { id: "q04", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "İtalya'nın başkenti neresidir?",
    choices: ["Roma", "Milano", "Napoli", "Venedik"],
    acceptedAnswers: ["Roma", "Rome"] },
  { id: "q05", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "Almanya'nın başkenti neresidir?",
    choices: ["Berlin", "Münih", "Hamburg", "Frankfurt"],
    acceptedAnswers: ["Berlin"] },
  { id: "q06", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "İspanya'nın başkenti neresidir?",
    choices: ["Madrid", "Barselona", "Sevilla", "Valencia"],
    acceptedAnswers: ["Madrid"] },
  { id: "q07", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "Rusya'nın başkenti neresidir?",
    choices: ["Moskova", "St. Petersburg", "Kazan", "Soçi"],
    acceptedAnswers: ["Moskova", "Moscow"] },
  { id: "q08", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "Mısır'ın başkenti neresidir?",
    choices: ["Kahire", "İskenderiye", "Lüksor", "Asvan"],
    acceptedAnswers: ["Kahire", "Cairo"] },
  { id: "q09", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "Amerika Birleşik Devletleri'nin başkenti neresidir?",
    choices: ["Washington D.C.", "New York", "Los Angeles", "Chicago"],
    acceptedAnswers: ["Washington D.C.", "Washington", "Washington DC"] },
  { id: "q10", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "Çin'in başkenti neresidir?",
    choices: ["Pekin", "Şangay", "Hong Kong", "Guangzhou"],
    acceptedAnswers: ["Pekin", "Beijing"] },
  { id: "q11", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "İngiltere'nin başkenti neresidir?",
    choices: ["Londra", "Manchester", "Liverpool", "Birmingham"],
    acceptedAnswers: ["Londra", "London"] },
  { id: "q12", family: "country_to_capital_mc", difficulty: "easy",
    prompt: "Yunanistan'ın başkenti neresidir?",
    choices: ["Atina", "Selanik", "Patra", "Korfu"],
    acceptedAnswers: ["Atina", "Athens"] },
  { id: "q13", family: "country_to_capital_mc", difficulty: "medium",
    prompt: "Hindistan'ın başkenti neresidir?",
    choices: ["Yeni Delhi", "Mumbai", "Kolkata", "Chennai"],
    acceptedAnswers: ["Yeni Delhi", "Delhi", "New Delhi"] },
  { id: "q14", family: "country_to_capital_mc", difficulty: "medium",
    prompt: "Kanada'nın başkenti neresidir?",
    choices: ["Ottawa", "Toronto", "Montreal", "Vancouver"],
    acceptedAnswers: ["Ottawa"] },

  // ── physical geography: rivers ───────────────────────────────────────────
  { id: "q15", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Mısır'dan geçen, eski uygarlıkların beşiği sayılan büyük nehir hangisidir?",
    choices: ["Nil", "Kongo", "Niger", "Zambezi"],
    acceptedAnswers: ["Nil", "Nile"] },
  { id: "q16", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Güney Amerika'nın büyük yağmur ormanlarından geçen nehir hangisidir?",
    choices: ["Amazon", "Orinoco", "Paraná", "Magdalena"],
    acceptedAnswers: ["Amazon"] },
  { id: "q17", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Çin'de yer alan ve Asya'nın en uzun nehri olan hangisidir?",
    choices: ["Yangtze", "Sarı Irmak", "Mekong", "İndus"],
    acceptedAnswers: ["Yangtze", "Yangçe", "Çangciang"] },
  { id: "q18", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Hindistan'dan geçen, Hindular için kutsal sayılan nehir hangisidir?",
    choices: ["Ganj", "İndus", "Brahmaputra", "Godavari"],
    acceptedAnswers: ["Ganj", "Ganga", "Ganges"] },
  { id: "q19", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Birçok Avrupa ülkesinden geçip Karadeniz'e dökülen nehir hangisidir?",
    choices: ["Tuna", "Ren", "Volga", "Elbe"],
    acceptedAnswers: ["Tuna", "Danube", "Donau"] },
  { id: "q20", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Türkiye'nin en uzun nehri hangisidir?",
    choices: ["Kızılırmak", "Fırat", "Yeşilırmak", "Sakarya"],
    acceptedAnswers: ["Kızılırmak", "Kizilirmak"] },
  { id: "q21", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Paris şehrini ortadan ikiye bölen nehir hangisidir?",
    choices: ["Sen", "Loire", "Rhône", "Garonne"],
    acceptedAnswers: ["Sen", "Seine"] },
  { id: "q22", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Londra'dan geçen, Britanya'nın simge nehri hangisidir?",
    choices: ["Thames", "Severn", "Mersey", "Tyne"],
    acceptedAnswers: ["Thames", "Tems"] },

  // ── physical geography: mountains ────────────────────────────────────────
  { id: "q23", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Everest Dağı hangi sıradağda yer alır?",
    choices: ["Himalayalar", "Alpler", "And Dağları", "Karpatlar"],
    acceptedAnswers: ["Himalayalar", "Himalaya", "Himalayas"] },
  { id: "q24", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Afrika'nın en yüksek dağı hangisidir?",
    choices: ["Kilimanjaro", "Kenya Dağı", "Ras Daşen", "Atlas"],
    acceptedAnswers: ["Kilimanjaro", "Kilimancaro"] },
  { id: "q25", family: "physical_geo_mc", difficulty: "medium",
    prompt: "Güney Amerika'nın en yüksek dağı hangisidir?",
    choices: ["Aconcagua", "Chimborazo", "Huascarán", "Cotopaxi"],
    acceptedAnswers: ["Aconcagua"] },
  { id: "q26", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Türkiye'nin en yüksek dağı hangisidir?",
    choices: ["Ağrı Dağı", "Kaçkar", "Süphan", "Erciyes"],
    acceptedAnswers: ["Ağrı Dağı", "Ağrı", "Agri Dagi", "Agri", "Ararat"] },
  { id: "q27", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Alp Dağları başlıca hangi kıtada yer alır?",
    choices: ["Avrupa", "Asya", "Afrika", "Amerika"],
    acceptedAnswers: ["Avrupa", "Europe"] },
  { id: "q28", family: "physical_geo_mc", difficulty: "easy",
    prompt: "And Dağları hangi kıtada yer alır?",
    choices: ["Güney Amerika", "Kuzey Amerika", "Asya", "Avrupa"],
    acceptedAnswers: ["Güney Amerika", "Guney Amerika", "South America"] },

  // ── physical geography: deserts ──────────────────────────────────────────
  { id: "q29", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Sahra Çölü hangi kıtada yer alır?",
    choices: ["Afrika", "Asya", "Avustralya", "Güney Amerika"],
    acceptedAnswers: ["Afrika", "Africa"] },
  { id: "q30", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Gobi Çölü hangi kıtada yer alır?",
    choices: ["Asya", "Afrika", "Avustralya", "Avrupa"],
    acceptedAnswers: ["Asya", "Asia"] },
  { id: "q31", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Kalahari Çölü hangi kıtada yer alır?",
    choices: ["Afrika", "Asya", "Okyanusya", "Güney Amerika"],
    acceptedAnswers: ["Afrika", "Africa"] },

  // ── physical geography: seas, straits, canals ────────────────────────────
  { id: "q32", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Türkiye'nin kuzeyinde bulunan deniz hangisidir?",
    choices: ["Karadeniz", "Akdeniz", "Ege Denizi", "Marmara Denizi"],
    acceptedAnswers: ["Karadeniz", "Kara Deniz", "Black Sea"] },
  { id: "q33", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Türkiye'nin batısında bulunan deniz hangisidir?",
    choices: ["Ege Denizi", "Akdeniz", "Karadeniz", "Marmara Denizi"],
    acceptedAnswers: ["Ege Denizi", "Ege", "Aegean Sea"] },
  { id: "q34", family: "physical_geo_mc", difficulty: "easy",
    prompt: "İstanbul Boğazı hangi iki denizi birbirine bağlar?",
    choices: ["Karadeniz ve Marmara", "Karadeniz ve Ege", "Akdeniz ve Marmara", "Marmara ve Ege"],
    acceptedAnswers: ["Karadeniz ve Marmara", "Marmara ve Karadeniz"] },
  { id: "q35", family: "physical_geo_mc", difficulty: "easy",
    prompt: "İstanbul Boğazı hangi iki kıtayı birbirinden ayırır?",
    choices: ["Avrupa ve Asya", "Asya ve Afrika", "Avrupa ve Afrika", "Kuzey ve Güney Amerika"],
    acceptedAnswers: ["Avrupa ve Asya", "Asya ve Avrupa"] },
  { id: "q36", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Çanakkale Boğazı hangi iki denizi birbirine bağlar?",
    choices: ["Marmara ve Ege", "Karadeniz ve Marmara", "Akdeniz ve Ege", "Marmara ve Akdeniz"],
    acceptedAnswers: ["Marmara ve Ege", "Ege ve Marmara"] },
  { id: "q37", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Cebelitarık Boğazı hangi iki kıtayı birbirinden ayırır?",
    choices: ["Avrupa ve Afrika", "Asya ve Afrika", "Avrupa ve Asya", "Kuzey ve Güney Amerika"],
    acceptedAnswers: ["Avrupa ve Afrika", "Afrika ve Avrupa"] },
  { id: "q38", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Süveyş Kanalı hangi iki denizi birbirine bağlar?",
    choices: ["Akdeniz ve Kızıldeniz", "Karadeniz ve Akdeniz", "Akdeniz ve Hazar", "Kızıldeniz ve Arap Denizi"],
    acceptedAnswers: ["Akdeniz ve Kızıldeniz", "Kızıldeniz ve Akdeniz"] },
  { id: "q39", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Panama Kanalı hangi iki okyanusu birbirine bağlar?",
    choices: ["Pasifik ve Atlas", "Pasifik ve Hint", "Atlas ve Hint", "Pasifik ve Arktik"],
    acceptedAnswers: ["Pasifik ve Atlas", "Atlas ve Pasifik", "Büyük Okyanus ve Atlas"] },
  { id: "q40", family: "physical_geo_mc", difficulty: "medium",
    prompt: "Kızıldeniz hangi iki kıtanın arasında yer alır?",
    choices: ["Afrika ve Asya", "Avrupa ve Asya", "Avrupa ve Afrika", "Asya ve Okyanusya"],
    acceptedAnswers: ["Afrika ve Asya", "Asya ve Afrika"] },

  // ── physical geography: lakes, islands ───────────────────────────────────
  { id: "q41", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Türkiye'nin en büyük gölü hangisidir?",
    choices: ["Van Gölü", "Tuz Gölü", "Beyşehir Gölü", "Eğirdir Gölü"],
    acceptedAnswers: ["Van Gölü", "Van"] },
  { id: "q42", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Akdeniz'in en büyük adası hangisidir?",
    choices: ["Sicilya", "Sardunya", "Kıbrıs", "Girit"],
    acceptedAnswers: ["Sicilya", "Sicily"] },
  { id: "q43", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Britanya Adaları'nın en büyük adası hangisidir?",
    choices: ["Büyük Britanya", "İrlanda", "Man Adası", "Wight"],
    acceptedAnswers: ["Büyük Britanya", "Buyuk Britanya", "Great Britain"] },

  // ── physical geography: continents-as-borders, mixed ─────────────────────
  { id: "q44", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Avrupa'nın en uzun nehri hangisidir?",
    choices: ["Volga", "Tuna", "Ren", "Don"],
    acceptedAnswers: ["Volga"] },
  { id: "q45", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Ural Dağları hangi iki kıta arasında doğal sınır oluşturur?",
    choices: ["Avrupa-Asya", "Asya-Afrika", "Avrupa-Afrika", "Asya-Okyanusya"],
    acceptedAnswers: ["Avrupa-Asya", "Avrupa Asya", "Asya-Avrupa"] },
  { id: "q46", family: "physical_geo_mc", difficulty: "medium",
    prompt: "İndus Nehri ağırlıklı olarak hangi ülkede yer alır?",
    choices: ["Pakistan", "Hindistan", "Afganistan", "Bangladeş"],
    acceptedAnswers: ["Pakistan"] },
  { id: "q47", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Dicle ve Fırat nehirleri ağırlıklı olarak hangi ülkeden doğar?",
    choices: ["Türkiye", "Irak", "İran", "Suriye"],
    acceptedAnswers: ["Türkiye", "Turkey"] },
  { id: "q48", family: "physical_geo_mc", difficulty: "medium",
    prompt: "Ren (Rhein) Nehri başlıca hangi ülkelerden geçer?",
    choices: ["Almanya ve Hollanda", "Fransa ve İspanya", "İtalya ve Avusturya", "Polonya ve Çekya"],
    acceptedAnswers: ["Almanya ve Hollanda", "Hollanda ve Almanya"] },
  { id: "q49", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Mississippi Nehri hangi ülkede akar?",
    choices: ["ABD", "Kanada", "Meksika", "Brezilya"],
    acceptedAnswers: ["ABD", "Amerika", "Amerika Birleşik Devletleri", "USA", "United States"] },

  // ── physical geography: climate ──────────────────────────────────────────
  { id: "q50", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Akdeniz ikliminde yazlar genellikle nasıl geçer?",
    choices: ["Sıcak ve kurak", "Soğuk ve karlı", "Serin ve yağışlı", "Ilık ve nemli"],
    acceptedAnswers: ["Sıcak ve kurak"] },
  { id: "q51", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Buzul (kutup) iklimi en geniş alanda hangi kıtada görülür?",
    choices: ["Antarktika", "Afrika", "Avustralya", "Güney Amerika"],
    acceptedAnswers: ["Antarktika", "Antarctica"] },
  { id: "q52", family: "physical_geo_mc", difficulty: "easy",
    prompt: "Tropikal yağmur ormanları en çok hangi kuşakta görülür?",
    choices: ["Ekvator çevresinde", "Kutup çevresinde", "Çöl kuşağında", "Ilıman kuşakta"],
    acceptedAnswers: ["Ekvator çevresinde", "Ekvator"] },

  // ── country location & features (region) ─────────────────────────────────
  { id: "q53", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisinin denize kıyısı yoktur?",
    choices: ["İsviçre", "Portekiz", "Norveç", "Yunanistan"],
    acceptedAnswers: ["İsviçre", "Isvicre", "Switzerland"] },
  { id: "q54", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi hem Avrupa hem Asya'da topraklara sahiptir?",
    choices: ["Türkiye", "Yunanistan", "İtalya", "Mısır"],
    acceptedAnswers: ["Türkiye", "Turkiye", "Turkey"] },
  { id: "q55", family: "region_mc", difficulty: "medium",
    prompt: "Güney Amerika'nın batı kıyısında uzun ve dar biçimde uzanan ülke hangisidir?",
    choices: ["Şili", "Brezilya", "Arjantin", "Bolivya"],
    acceptedAnswers: ["Şili", "Sili", "Chile"] },
  { id: "q56", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi bir ada ülkesidir?",
    choices: ["Madagaskar", "Şili", "Vietnam", "Portekiz"],
    acceptedAnswers: ["Madagaskar", "Madagascar"] },
  { id: "q57", family: "region_mc", difficulty: "easy",
    prompt: "İber Yarımadası'nda yer alan iki ülke hangileridir?",
    choices: ["İspanya ve Portekiz", "Fransa ve İspanya", "Portekiz ve Fransa", "İtalya ve İspanya"],
    acceptedAnswers: ["İspanya ve Portekiz", "Portekiz ve İspanya"] },
  { id: "q58", family: "region_mc", difficulty: "easy",
    prompt: "İskandinav Yarımadası'nda yer alan iki ülke hangileridir?",
    choices: ["İsveç ve Norveç", "Norveç ve Finlandiya", "Danimarka ve İsveç", "Finlandiya ve İzlanda"],
    acceptedAnswers: ["İsveç ve Norveç", "Norveç ve İsveç"] },
  { id: "q59", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdakilerden hangisi bir İskandinav ülkesi DEĞİLDİR?",
    choices: ["Hollanda", "İsveç", "Norveç", "Danimarka"],
    acceptedAnswers: ["Hollanda", "Netherlands"] },
  { id: "q60", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdakilerden hangisi bir Balkan ülkesi DEĞİLDİR?",
    choices: ["Polonya", "Sırbistan", "Bulgaristan", "Arnavutluk"],
    acceptedAnswers: ["Polonya", "Poland"] },
  { id: "q61", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi Güney Yarımküre'de yer alır?",
    choices: ["Avustralya", "İtalya", "Japonya", "Kanada"],
    acceptedAnswers: ["Avustralya", "Australia"] },
  { id: "q62", family: "region_mc", difficulty: "medium",
    prompt: "Ekvator aşağıdaki ülkelerden hangisinin içinden geçer?",
    choices: ["Ekvador", "Türkiye", "Mısır", "İspanya"],
    acceptedAnswers: ["Ekvador", "Ecuador"] },
  { id: "q63", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki şehirlerden hangisi iki kıtaya yayılmıştır?",
    choices: ["İstanbul", "Roma", "Atina", "Kahire"],
    acceptedAnswers: ["İstanbul", "Istanbul"] },
  { id: "q64", family: "region_mc", difficulty: "medium",
    prompt: "Aşağıdaki ülkelerden hangisi binlerce adadan oluşan bir takımadadır?",
    choices: ["Endonezya", "Şili", "Vietnam", "Portekiz"],
    acceptedAnswers: ["Endonezya", "Indonesia"] },
  { id: "q65", family: "region_mc", difficulty: "medium",
    prompt: "Dünyanın en büyük adası olan Grönland hangi ülkeye bağlıdır?",
    choices: ["Danimarka", "Norveç", "Kanada", "İzlanda"],
    acceptedAnswers: ["Danimarka", "Denmark"] },
  { id: "q66", family: "region_mc", difficulty: "easy",
    prompt: "Kıbrıs hangi denizde yer alan bir adadır?",
    choices: ["Akdeniz", "Karadeniz", "Ege Denizi", "Kızıldeniz"],
    acceptedAnswers: ["Akdeniz", "Mediterranean"] },
  { id: "q67", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisinin hem Karadeniz'e hem Akdeniz'e kıyısı vardır?",
    choices: ["Türkiye", "Yunanistan", "Bulgaristan", "Mısır"],
    acceptedAnswers: ["Türkiye", "Turkiye", "Turkey"] },
  { id: "q68", family: "region_mc", difficulty: "easy",
    prompt: "Tarihte Mezopotamya olarak bilinen bölge hangi iki nehir arasındadır?",
    choices: ["Dicle ve Fırat", "Nil ve Kongo", "Ganj ve İndus", "Tuna ve Ren"],
    acceptedAnswers: ["Dicle ve Fırat", "Fırat ve Dicle"] },
  { id: "q69", family: "region_mc", difficulty: "medium",
    prompt: "Anadolu, tarihte başka hangi adla da bilinir?",
    choices: ["Küçük Asya", "Mezopotamya", "Levant", "Kafkasya"],
    acceptedAnswers: ["Küçük Asya", "Kucuk Asya", "Anatolia", "Asia Minor"] },
  { id: "q70", family: "region_mc", difficulty: "medium",
    prompt: "Aşağıdaki ülkelerden hangisi bir yarımada üzerinde yer alır?",
    choices: ["Güney Kore", "Moğolistan", "Kazakistan", "Çad"],
    acceptedAnswers: ["Güney Kore", "Guney Kore", "Kore", "South Korea"] },
  { id: "q71", family: "region_mc", difficulty: "easy",
    prompt: "Avrupa ile Afrika kıtaları arasında yer alan deniz hangisidir?",
    choices: ["Akdeniz", "Karadeniz", "Kızıldeniz", "Baltık Denizi"],
    acceptedAnswers: ["Akdeniz", "Mediterranean"] },
  { id: "q72", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi Orta Doğu'da yer alır?",
    choices: ["Suudi Arabistan", "İspanya", "Brezilya", "Tayland"],
    acceptedAnswers: ["Suudi Arabistan", "Saudi Arabia"] },
  { id: "q73", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi Güneydoğu Asya'da yer alır?",
    choices: ["Tayland", "Polonya", "Şili", "Fas"],
    acceptedAnswers: ["Tayland", "Thailand"] },
  { id: "q74", family: "region_mc", difficulty: "medium",
    prompt: "Aşağıdaki ülkelerden hangisi Kuzey Afrika'da yer alır?",
    choices: ["Cezayir", "Kenya", "Nijerya", "Gana"],
    acceptedAnswers: ["Cezayir", "Algeria"] },
  { id: "q75", family: "region_mc", difficulty: "medium",
    prompt: "Aşağıdaki ülkelerden hangisi Orta Amerika'da yer alır?",
    choices: ["Panama", "Kolombiya", "Venezuela", "Ekvador"],
    acceptedAnswers: ["Panama"] },
  { id: "q76", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdakilerden hangisi denize kıyısı olmayan bir Avrupa ülkesidir?",
    choices: ["Avusturya", "Portekiz", "Hırvatistan", "Yunanistan"],
    acceptedAnswers: ["Avusturya", "Austria"] },
  { id: "q77", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi tek başına bir kıta sayılır?",
    choices: ["Avustralya", "Brezilya", "Kanada", "Rusya"],
    acceptedAnswers: ["Avustralya", "Australia"] },
  { id: "q78", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi Güney Amerika'da yer alır?",
    choices: ["Peru", "Meksika", "İspanya", "Fas"],
    acceptedAnswers: ["Peru"] },
  { id: "q79", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi Afrika kıtasında yer alır?",
    choices: ["Kenya", "Tayland", "Şili", "Portekiz"],
    acceptedAnswers: ["Kenya"] },
  { id: "q80", family: "region_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi Avrupa'da yer alır?",
    choices: ["Portekiz", "Mısır", "Tayland", "Peru"],
    acceptedAnswers: ["Portekiz", "Portugal"] },
  { id: "q81", family: "region_mc", difficulty: "medium",
    prompt: "Galapagos Adaları hangi ülkeye aittir?",
    choices: ["Ekvador", "Peru", "Şili", "Kolombiya"],
    acceptedAnswers: ["Ekvador", "Ecuador"] },
  { id: "q82", family: "region_mc", difficulty: "easy",
    prompt: "Avrupa'nın yüzölçümü en büyük ülkesi hangisidir?",
    choices: ["Rusya", "Ukrayna", "Fransa", "Almanya"],
    acceptedAnswers: ["Rusya", "Russia"] },

  // ── neighbours / borders ─────────────────────────────────────────────────
  { id: "q83", family: "neighbor_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi Türkiye ile sınır komşusudur?",
    choices: ["Gürcistan", "Mısır", "Romanya", "Ukrayna"],
    acceptedAnswers: ["Gürcistan", "Gurcistan", "Georgia"] },
  { id: "q84", family: "neighbor_mc", difficulty: "easy",
    prompt: "Türkiye'nin güneydeki sınır komşularından biri hangisidir?",
    choices: ["Suriye", "Lübnan", "İsrail", "Ürdün"],
    acceptedAnswers: ["Suriye", "Syria"] },
  { id: "q85", family: "neighbor_mc", difficulty: "easy",
    prompt: "Aşağıdakilerden hangisi Türkiye'nin sınır komşusu DEĞİLDİR?",
    choices: ["Mısır", "Ermenistan", "Bulgaristan", "İran"],
    acceptedAnswers: ["Mısır", "Misir", "Egypt"] },
  { id: "q86", family: "neighbor_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi Almanya ile sınır komşusudur?",
    choices: ["Polonya", "Romanya", "İspanya", "Norveç"],
    acceptedAnswers: ["Polonya", "Poland"] },
  { id: "q87", family: "neighbor_mc", difficulty: "easy",
    prompt: "Portekiz'in tek kara sınırına sahip olduğu ülke hangisidir?",
    choices: ["İspanya", "Fransa", "Fas", "Andorra"],
    acceptedAnswers: ["İspanya", "Ispanya", "Spain"] },
  { id: "q88", family: "neighbor_mc", difficulty: "easy",
    prompt: "Kanada'nın tek kara sınırına sahip olduğu ülke hangisidir?",
    choices: ["ABD", "Meksika", "Rusya", "Grönland"],
    acceptedAnswers: ["ABD", "Amerika", "Amerika Birleşik Devletleri", "USA", "United States"] },
  { id: "q89", family: "neighbor_mc", difficulty: "easy",
    prompt: "ABD'nin güney komşusu hangi ülkedir?",
    choices: ["Meksika", "Kanada", "Guatemala", "Küba"],
    acceptedAnswers: ["Meksika", "Mexico"] },
  { id: "q90", family: "neighbor_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi Fransa ile sınır komşusudur?",
    choices: ["Almanya", "Portekiz", "İrlanda", "Yunanistan"],
    acceptedAnswers: ["Almanya", "Germany"] },
  { id: "q91", family: "neighbor_mc", difficulty: "easy",
    prompt: "İspanya hangi ülke ile uzun bir kara sınırı paylaşır?",
    choices: ["Fransa", "İtalya", "Almanya", "Belçika"],
    acceptedAnswers: ["Fransa", "France"] },
  { id: "q92", family: "neighbor_mc", difficulty: "medium",
    prompt: "Aşağıdaki ülkelerden hangisi İsviçre ile sınır komşusudur?",
    choices: ["İtalya", "İspanya", "İngiltere", "Yunanistan"],
    acceptedAnswers: ["İtalya", "Italya", "Italy"] },
  { id: "q93", family: "neighbor_mc", difficulty: "medium",
    prompt: "Aşağıdaki ülkelerden hangisi Yunanistan ile sınır komşusudur?",
    choices: ["Bulgaristan", "İtalya", "Romanya", "Sırbistan"],
    acceptedAnswers: ["Bulgaristan", "Bulgaria"] },
  { id: "q94", family: "neighbor_mc", difficulty: "easy",
    prompt: "Aşağıdaki ülkelerden hangisi İran ile sınır komşusudur?",
    choices: ["Türkiye", "Mısır", "Suudi Arabistan", "Yunanistan"],
    acceptedAnswers: ["Türkiye", "Turkiye", "Turkey"] },
  { id: "q95", family: "neighbor_mc", difficulty: "medium",
    prompt: "İrlanda Adası'nda İrlanda Cumhuriyeti hangi ülke ile kara sınırı paylaşır?",
    choices: ["Birleşik Krallık", "Fransa", "İzlanda", "Hollanda"],
    acceptedAnswers: ["Birleşik Krallık", "Birlesik Krallik", "İngiltere", "Ingiltere", "UK", "United Kingdom"] },

  // ── landmarks, ancient cities, world heritage, famous cities ─────────────
  { id: "q96", family: "landmark_mc", difficulty: "easy",
    prompt: "Eyfel Kulesi hangi şehirde bulunur?",
    choices: ["Paris", "Londra", "Berlin", "Madrid"],
    acceptedAnswers: ["Paris"] },
  { id: "q97", family: "landmark_mc", difficulty: "easy",
    prompt: "Big Ben adlı saat kulesi hangi şehirdedir?",
    choices: ["Londra", "Edinburgh", "Manchester", "Dublin"],
    acceptedAnswers: ["Londra", "London"] },
  { id: "q98", family: "landmark_mc", difficulty: "easy",
    prompt: "Kolezyum hangi şehirde yer alır?",
    choices: ["Roma", "Atina", "Napoli", "İstanbul"],
    acceptedAnswers: ["Roma", "Rome"] },
  { id: "q99", family: "landmark_mc", difficulty: "easy",
    prompt: "Akropolis hangi şehirde bulunur?",
    choices: ["Atina", "Roma", "İstanbul", "Selanik"],
    acceptedAnswers: ["Atina", "Athens"] },
  { id: "q100", family: "landmark_mc", difficulty: "easy",
    prompt: "Ayasofya hangi şehirde bulunur?",
    choices: ["İstanbul", "Ankara", "İzmir", "Bursa"],
    acceptedAnswers: ["İstanbul", "Istanbul"] },
  { id: "q101", family: "landmark_mc", difficulty: "easy",
    prompt: "Vatikan hangi şehrin içinde yer alır?",
    choices: ["Roma", "Floransa", "Cenova", "Milano"],
    acceptedAnswers: ["Roma", "Rome"] },
  { id: "q102", family: "landmark_mc", difficulty: "easy",
    prompt: "Machu Picchu antik kenti hangi ülkededir?",
    choices: ["Peru", "Şili", "Bolivya", "Meksika"],
    acceptedAnswers: ["Peru"] },
  { id: "q103", family: "landmark_mc", difficulty: "easy",
    prompt: "Petra antik kenti hangi ülkede yer alır?",
    choices: ["Ürdün", "İsrail", "Mısır", "Suriye"],
    acceptedAnswers: ["Ürdün", "Urdun", "Jordan"] },
  { id: "q104", family: "landmark_mc", difficulty: "easy",
    prompt: "Tac Mahal hangi ülkede bulunur?",
    choices: ["Hindistan", "Pakistan", "Nepal", "Bangladeş"],
    acceptedAnswers: ["Hindistan", "India"] },
  { id: "q105", family: "landmark_mc", difficulty: "easy",
    prompt: "Dünyanın en uzun savunma duvarı olarak bilinen tarihî yapı hangisidir?",
    choices: ["Çin Seddi", "Hadrian Duvarı", "Berlin Duvarı", "Konstantinopolis Surları"],
    acceptedAnswers: ["Çin Seddi", "Cin Seddi", "Great Wall"] },
  { id: "q106", family: "landmark_mc", difficulty: "easy",
    prompt: "Kapadokya hangi ülkede yer alır?",
    choices: ["Türkiye", "Yunanistan", "İran", "Gürcistan"],
    acceptedAnswers: ["Türkiye", "Turkiye", "Turkey"] },
  { id: "q107", family: "landmark_mc", difficulty: "easy",
    prompt: "Gize Piramitleri hangi ülkede bulunur?",
    choices: ["Mısır", "Sudan", "Irak", "Meksika"],
    acceptedAnswers: ["Mısır", "Misir", "Egypt"] },
  { id: "q108", family: "landmark_mc", difficulty: "easy",
    prompt: "Özgürlük Heykeli hangi şehirde bulunur?",
    choices: ["New York", "Washington", "Boston", "Chicago"],
    acceptedAnswers: ["New York", "Newyork"] },
  { id: "q109", family: "landmark_mc", difficulty: "medium",
    prompt: "Dev Kurtarıcı İsa Heykeli hangi şehirde bulunur?",
    choices: ["Rio de Janeiro", "São Paulo", "Lima", "Buenos Aires"],
    acceptedAnswers: ["Rio de Janeiro", "Rio"] },
  { id: "q110", family: "landmark_mc", difficulty: "easy",
    prompt: "Eğik (Pisa) Kulesi hangi ülkede bulunur?",
    choices: ["İtalya", "İspanya", "Fransa", "Yunanistan"],
    acceptedAnswers: ["İtalya", "Italya", "Italy"] },
  { id: "q111", family: "landmark_mc", difficulty: "medium",
    prompt: "Tarih öncesi taş anıt Stonehenge hangi ülkededir?",
    choices: ["İngiltere", "İrlanda", "Fransa", "Almanya"],
    acceptedAnswers: ["İngiltere", "Ingiltere", "Birleşik Krallık", "England", "UK"] },
  { id: "q112", family: "landmark_mc", difficulty: "easy",
    prompt: "Brandenburg Kapısı hangi şehirde bulunur?",
    choices: ["Berlin", "Münih", "Viyana", "Varşova"],
    acceptedAnswers: ["Berlin"] },
  { id: "q113", family: "landmark_mc", difficulty: "medium",
    prompt: "Gaudí'nin ünlü Sagrada Familia kilisesi hangi şehirdedir?",
    choices: ["Barselona", "Madrid", "Sevilla", "Valensiya"],
    acceptedAnswers: ["Barselona", "Barcelona"] },
  { id: "q114", family: "landmark_mc", difficulty: "easy",
    prompt: "Dünyanın en yüksek binası Burç Halife hangi şehirdedir?",
    choices: ["Dubai", "Abu Dabi", "Doha", "Riyad"],
    acceptedAnswers: ["Dubai"] },
  { id: "q115", family: "landmark_mc", difficulty: "medium",
    prompt: "Kızıl Meydan hangi şehirde yer alır?",
    choices: ["Moskova", "St. Petersburg", "Kiev", "Minsk"],
    acceptedAnswers: ["Moskova", "Moscow"] },
  { id: "q116", family: "landmark_mc", difficulty: "medium",
    prompt: "Angkor Wat tapınak kompleksi hangi ülkededir?",
    choices: ["Kamboçya", "Tayland", "Vietnam", "Laos"],
    acceptedAnswers: ["Kamboçya", "Kambocya", "Cambodia"] },
  { id: "q117", family: "landmark_mc", difficulty: "medium",
    prompt: "Nemrut Dağı'ndaki dev heykeller hangi ülkededir?",
    choices: ["Türkiye", "İran", "Irak", "Yunanistan"],
    acceptedAnswers: ["Türkiye", "Turkiye", "Turkey"] },
  { id: "q118", family: "landmark_mc", difficulty: "easy",
    prompt: "Efes Antik Kenti hangi ülkede yer alır?",
    choices: ["Türkiye", "Yunanistan", "İtalya", "Mısır"],
    acceptedAnswers: ["Türkiye", "Turkiye", "Turkey"] },
  { id: "q119", family: "landmark_mc", difficulty: "easy",
    prompt: "Beyaz travertenleriyle ünlü Pamukkale hangi ülkededir?",
    choices: ["Türkiye", "Yunanistan", "İtalya", "İspanya"],
    acceptedAnswers: ["Türkiye", "Turkiye", "Turkey"] },
  { id: "q120", family: "landmark_mc", difficulty: "easy",
    prompt: "Louvre Müzesi hangi şehirde bulunur?",
    choices: ["Paris", "Londra", "Roma", "Madrid"],
    acceptedAnswers: ["Paris"] },
  { id: "q121", family: "landmark_mc", difficulty: "easy",
    prompt: "Buckingham Sarayı hangi şehirde yer alır?",
    choices: ["Londra", "Paris", "Brüksel", "Amsterdam"],
    acceptedAnswers: ["Londra", "London"] },
  { id: "q122", family: "landmark_mc", difficulty: "easy",
    prompt: "Empire State Binası hangi şehirde bulunur?",
    choices: ["New York", "Chicago", "Toronto", "Los Angeles"],
    acceptedAnswers: ["New York", "Newyork"] },
  { id: "q123", family: "landmark_mc", difficulty: "medium",
    prompt: "Elhamra (Alhambra) Sarayı hangi ülkededir?",
    choices: ["İspanya", "Fas", "Portekiz", "İtalya"],
    acceptedAnswers: ["İspanya", "Ispanya", "Spain"] },
  { id: "q124", family: "landmark_mc", difficulty: "easy",
    prompt: "Notre-Dame Katedrali hangi şehirde bulunur?",
    choices: ["Paris", "Roma", "Köln", "Viyana"],
    acceptedAnswers: ["Paris"] },
  { id: "q125", family: "landmark_mc", difficulty: "medium",
    prompt: "Petronas İkiz Kuleleri hangi şehirde yer alır?",
    choices: ["Kuala Lumpur", "Singapur", "Jakarta", "Bangkok"],
    acceptedAnswers: ["Kuala Lumpur"] },
  { id: "q126", family: "landmark_mc", difficulty: "hard",
    prompt: "Paskalya Adası'ndaki ünlü Moai heykelleri bugün hangi ülkeye bağlıdır?",
    choices: ["Şili", "Peru", "Yeni Zelanda", "Meksika"],
    acceptedAnswers: ["Şili", "Sili", "Chile"] },
  { id: "q127", family: "landmark_mc", difficulty: "medium",
    prompt: "Kremlin hangi şehirde yer alır?",
    choices: ["Moskova", "Kiev", "Varşova", "Prag"],
    acceptedAnswers: ["Moskova", "Moscow"] },

  // ── world records (explicit, undisputed metric) ──────────────────────────
  { id: "q128", family: "world_record_mc", difficulty: "easy",
    prompt: "Dünyanın en büyük sıcak çölü hangisidir?",
    choices: ["Sahra", "Gobi", "Kalahari", "Atacama"],
    acceptedAnswers: ["Sahra", "Sahara"] },
  { id: "q129", family: "world_record_mc", difficulty: "easy",
    prompt: "Deniz seviyesinden yüksekliğiyle dünyanın en yüksek dağı hangisidir?",
    choices: ["Everest", "K2", "Kilimanjaro", "Aconcagua"],
    acceptedAnswers: ["Everest", "Mount Everest"] },
  { id: "q130", family: "world_record_mc", difficulty: "easy",
    prompt: "Yüzölçümü bakımından dünyanın en büyük okyanusu hangisidir?",
    choices: ["Büyük Okyanus", "Atlas Okyanusu", "Hint Okyanusu", "Arktik Okyanus"],
    acceptedAnswers: ["Büyük Okyanus", "Pasifik", "Pacific", "Pasifik Okyanusu"] },
  { id: "q131", family: "world_record_mc", difficulty: "easy",
    prompt: "Yüzölçümü bakımından dünyanın en büyük kıtası hangisidir?",
    choices: ["Asya", "Afrika", "Kuzey Amerika", "Antarktika"],
    acceptedAnswers: ["Asya", "Asia"] },
  { id: "q132", family: "world_record_mc", difficulty: "easy",
    prompt: "Yüzölçümü bakımından dünyanın en küçük kıtası hangisidir?",
    choices: ["Avustralya", "Avrupa", "Antarktika", "Güney Amerika"],
    acceptedAnswers: ["Avustralya", "Okyanusya", "Australia"] },
  { id: "q133", family: "world_record_mc", difficulty: "easy",
    prompt: "Yüzölçümü bakımından dünyanın en büyük ülkesi hangisidir?",
    choices: ["Rusya", "Kanada", "Çin", "ABD"],
    acceptedAnswers: ["Rusya", "Russia"] },
  { id: "q134", family: "world_record_mc", difficulty: "medium",
    prompt: "Dünyanın en derin gölü hangisidir?",
    choices: ["Baykal Gölü", "Tanganika", "Hazar Denizi", "Victoria Gölü"],
    acceptedAnswers: ["Baykal Gölü", "Baykal", "Baikal", "Lake Baikal"] },
  { id: "q135", family: "world_record_mc", difficulty: "medium",
    prompt: "Aslında bir göl olan, yüzölçümü bakımından dünyanın en büyük su kütlesi hangisidir?",
    choices: ["Hazar Denizi", "Superior Gölü", "Victoria Gölü", "Baykal Gölü"],
    acceptedAnswers: ["Hazar Denizi", "Hazar", "Caspian", "Caspian Sea"] },
  { id: "q136", family: "world_record_mc", difficulty: "medium",
    prompt: "En az yağış alan, dünyanın en kurak çölü hangisidir?",
    choices: ["Atacama", "Sahra", "Gobi", "Kalahari"],
    acceptedAnswers: ["Atacama"] },
  { id: "q137", family: "world_record_mc", difficulty: "hard",
    prompt: "Dünya üzerinde kaydedilen en düşük hava sıcaklığı hangi kıtada ölçülmüştür?",
    choices: ["Antarktika", "Asya", "Kuzey Amerika", "Avrupa"],
    acceptedAnswers: ["Antarktika", "Antarctica"] },
  { id: "q138", family: "world_record_mc", difficulty: "hard",
    prompt: "Kesintisiz düşüşüyle dünyanın en yüksek şelalesi hangisidir?",
    choices: ["Angel Şelalesi", "Niagara Şelalesi", "Victoria Şelalesi", "Iguazu Şelalesi"],
    acceptedAnswers: ["Angel Şelalesi", "Angel", "Angel Falls", "Salto Angel"] },
  { id: "q139", family: "world_record_mc", difficulty: "medium",
    prompt: "Kara üzerindeki en uzun sıradağ hangisidir?",
    choices: ["And Dağları", "Himalayalar", "Kayalık Dağlar", "Alpler"],
    acceptedAnswers: ["And Dağları", "Andlar", "Andes"] },
  { id: "q140", family: "world_record_mc", difficulty: "medium",
    prompt: "Avustralya bir kıta sayıldığında, dünyanın en büyük adası hangisidir?",
    choices: ["Grönland", "Yeni Gine", "Borneo", "Madagaskar"],
    acceptedAnswers: ["Grönland", "Gronland", "Greenland"] },
  { id: "q141", family: "world_record_mc", difficulty: "easy",
    prompt: "Dünyanın en büyük yağmur ormanı hangisidir?",
    choices: ["Amazon", "Kongo", "Borneo", "Tayga"],
    acceptedAnswers: ["Amazon", "Amazon Yağmur Ormanı"] },
  { id: "q142", family: "world_record_mc", difficulty: "medium",
    prompt: "Dünyanın en büyük mercan resifi sistemi hangisidir?",
    choices: ["Büyük Set Resifi", "Belize Resifi", "Maldiv Resifi", "Kızıldeniz Resifi"],
    acceptedAnswers: ["Büyük Set Resifi", "Buyuk Set Resifi", "Great Barrier Reef"] },
  { id: "q143", family: "world_record_mc", difficulty: "hard",
    prompt: "Yüzölçümü bakımından dünyanın en büyük yarımadası hangisidir?",
    choices: ["Arabistan Yarımadası", "İskandinav Yarımadası", "İber Yarımadası", "Balkan Yarımadası"],
    acceptedAnswers: ["Arabistan Yarımadası", "Arabistan", "Arabian Peninsula"] },

  // ── history-linked geography (single-meaning years & civilisations) ──────
  { id: "q144", family: "history_geo_mc", difficulty: "medium",
    prompt: "Eyfel Kulesi hangi yıl tamamlandı?",
    choices: ["1889", "1850", "1901", "1925"],
    acceptedAnswers: ["1889"] },
  { id: "q145", family: "history_geo_mc", difficulty: "hard",
    prompt: "Süveyş Kanalı hangi yıl açıldı?",
    choices: ["1869", "1825", "1901", "1888"],
    acceptedAnswers: ["1869"] },
  { id: "q146", family: "history_geo_mc", difficulty: "medium",
    prompt: "Panama Kanalı hangi yıl açıldı?",
    choices: ["1914", "1869", "1890", "1936"],
    acceptedAnswers: ["1914"] },
  { id: "q147", family: "history_geo_mc", difficulty: "medium",
    prompt: "Sidney Opera Binası hangi yıl açıldı?",
    choices: ["1973", "1959", "1985", "2000"],
    acceptedAnswers: ["1973"] },
  { id: "q148", family: "history_geo_mc", difficulty: "easy",
    prompt: "Berlin Duvarı hangi yıl yıkıldı?",
    choices: ["1989", "1961", "1975", "1995"],
    acceptedAnswers: ["1989"] },
  { id: "q149", family: "history_geo_mc", difficulty: "easy",
    prompt: "Kristof Kolomb, Amerika kıtasına ilk kez hangi yıl ulaştı?",
    choices: ["1492", "1453", "1521", "1607"],
    acceptedAnswers: ["1492"] },
  { id: "q150", family: "history_geo_mc", difficulty: "easy",
    prompt: "İstanbul'un fethi hangi yıl gerçekleşti?",
    choices: ["1453", "1492", "1071", "1683"],
    acceptedAnswers: ["1453"] },
  { id: "q151", family: "history_geo_mc", difficulty: "easy",
    prompt: "Türkiye Cumhuriyeti hangi yıl ilan edildi?",
    choices: ["1923", "1919", "1920", "1938"],
    acceptedAnswers: ["1923"] },
  { id: "q152", family: "history_geo_mc", difficulty: "easy",
    prompt: "Gize Piramitleri hangi uygarlık tarafından inşa edildi?",
    choices: ["Antik Mısır", "Antik Yunan", "Roma", "Pers"],
    acceptedAnswers: ["Antik Mısır", "Mısır", "Misir", "Mısırlılar"] },
  { id: "q153", family: "history_geo_mc", difficulty: "medium",
    prompt: "Kolezyum hangi antik uygarlık döneminde inşa edildi?",
    choices: ["Romalılar", "Yunanlar", "Mısırlılar", "Persler"],
    acceptedAnswers: ["Romalılar", "Roma", "Roma İmparatorluğu"] },
  { id: "q154", family: "history_geo_mc", difficulty: "medium",
    prompt: "Machu Picchu hangi uygarlık tarafından kuruldu?",
    choices: ["İnka", "Maya", "Aztek", "Olmek"],
    acceptedAnswers: ["İnka", "Inka", "Inca", "İnkalar"] },
  { id: "q155", family: "history_geo_mc", difficulty: "medium",
    prompt: "Vezüv Yanardağı'nın patlamasıyla küllerin altında kalan antik Roma kenti hangisidir?",
    choices: ["Pompei", "Troya", "Kartaca", "Efes"],
    acceptedAnswers: ["Pompei", "Pompeii"] },
  { id: "q156", family: "history_geo_mc", difficulty: "hard",
    prompt: "Tac Mahal hangi imparatorluk döneminde inşa edildi?",
    choices: ["Babür İmparatorluğu", "Osmanlı İmparatorluğu", "Pers İmparatorluğu", "Çin İmparatorluğu"],
    acceptedAnswers: ["Babür İmparatorluğu", "Babür", "Babur", "Mughal", "Mughal Empire"] },
  { id: "q157", family: "history_geo_mc", difficulty: "medium",
    prompt: "Ayasofya ilk olarak hangi imparatorluk döneminde inşa edildi?",
    choices: ["Bizans İmparatorluğu", "Osmanlı İmparatorluğu", "Roma Cumhuriyeti", "Pers İmparatorluğu"],
    acceptedAnswers: ["Bizans İmparatorluğu", "Bizans", "Doğu Roma", "Byzantine"] },

  // ── flag symbolism (educational, not pure flag→country recognition) ──────
  { id: "q158", family: "flag_symbol_mc", difficulty: "easy",
    prompt: "Bayrağında akçaağaç yaprağı bulunan ülke hangisidir?",
    choices: ["Kanada", "Avustralya", "Yeni Zelanda", "İrlanda"],
    acceptedAnswers: ["Kanada", "Canada"] },
  { id: "q159", family: "flag_symbol_mc", difficulty: "easy",
    prompt: "Bayrağında doğan güneş motifi bulunan ülke hangisidir?",
    choices: ["Japonya", "Çin", "Güney Kore", "Vietnam"],
    acceptedAnswers: ["Japonya", "Japan"] },
  { id: "q160", family: "flag_symbol_mc", difficulty: "medium",
    prompt: "Bayrağında ay-yıldız bulunan, Türkiye dışındaki ülke aşağıdakilerden hangisidir?",
    choices: ["Tunus", "İtalya", "Mısır", "Hindistan"],
    acceptedAnswers: ["Tunus", "Tunisia"] },
  { id: "q161", family: "flag_symbol_mc", difficulty: "easy",
    prompt: "Mavi-beyaz çizgili bayrağıyla bilinen Avrupa ülkesi hangisidir?",
    choices: ["Yunanistan", "İtalya", "Portekiz", "Almanya"],
    acceptedAnswers: ["Yunanistan", "Greece"] },
  { id: "q162", family: "flag_symbol_mc", difficulty: "medium",
    prompt: "Kırmızı zemin üzerinde beyaz haç bulunan İskandinav bayrağına sahip ülke hangisidir?",
    choices: ["Danimarka", "İsveç", "Norveç", "Finlandiya"],
    acceptedAnswers: ["Danimarka", "Denmark"] },
  { id: "q163", family: "flag_symbol_mc", difficulty: "medium",
    prompt: "Bayrağının ortasında mavi bir çark (Aşoka Çarkı) bulunan ülke hangisidir?",
    choices: ["Hindistan", "Pakistan", "Sri Lanka", "Nepal"],
    acceptedAnswers: ["Hindistan", "India"] },
  { id: "q164", family: "flag_symbol_mc", difficulty: "hard",
    prompt: "Bayrağında ejderha bulunan ülke aşağıdakilerden hangisidir?",
    choices: ["Butan", "Çin", "Vietnam", "Tayland"],
    acceptedAnswers: ["Butan", "Bhutan"] },
  { id: "q165", family: "flag_symbol_mc", difficulty: "medium",
    prompt: "Bayrağının ortasında sedir ağacı bulunan ülke hangisidir?",
    choices: ["Lübnan", "Suriye", "Ürdün", "İsrail"],
    acceptedAnswers: ["Lübnan", "Lubnan", "Lebanon"] },
  { id: "q166", family: "flag_symbol_mc", difficulty: "medium",
    prompt: "Bayrağının ortasında bir kartal ve yılan motifi bulunan ülke hangisidir?",
    choices: ["Meksika", "İspanya", "Arjantin", "Brezilya"],
    acceptedAnswers: ["Meksika", "Mexico"] },
  { id: "q167", family: "flag_symbol_mc", difficulty: "medium",
    prompt: "Bayrağında Davut Yıldızı bulunan ülke hangisidir?",
    choices: ["İsrail", "Lübnan", "Türkiye", "Yunanistan"],
    acceptedAnswers: ["İsrail", "Israil", "Israel"] },
];

// ─────────────────────────────────────────────────────────────────────────────
// Type race — free-text "write a country" prompts
//   • country_starts_with_letter — letters with enough valid answers to be fair
//   • country_by_criteria        — region / coast / feature based
// ─────────────────────────────────────────────────────────────────────────────

export interface TypeRaceBankEntry {
  id:               string;
  prompt:           string;
  /** Free-text family — drives the planner's family anti-repetition. */
  family:           ConquestWriteFamily;
  /** Set only for `country_starts_with_letter`; drives letter anti-repetition. */
  letter?:          string;
  difficulty:       ConquestQuestionDifficulty;
  /** Every accepted country/answer.  First correct typist wins. */
  acceptedAnswers:  string[];
}

export const CONQUEST_TYPE_RACE_BANK: TypeRaceBankEntry[] = [
  { id: "tr01", family: "country_starts_with_letter", letter: "A", difficulty: "easy",
    prompt: "A harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Almanya", "Avusturya", "Avustralya", "Arnavutluk", "Azerbaycan",
      "Afganistan", "Andorra", "Angola", "Arjantin", "Amerika", "ABD",
      "Aruba", "Antigua",
    ] },
  { id: "tr02", family: "country_starts_with_letter", letter: "B", difficulty: "easy",
    prompt: "B harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Brezilya", "Bulgaristan", "Belçika", "Bangladeş", "Bolivya",
      "Bahreyn", "Belarus", "Birleşik Krallık", "Bosna Hersek", "Botsvana",
      "Butan", "Burkina Faso", "Burundi", "Bahamas",
    ] },
  { id: "tr03", family: "country_starts_with_letter", letter: "F", difficulty: "medium",
    prompt: "F harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Fransa", "Finlandiya", "Filipinler", "Fas", "Filistin", "Fiji",
    ] },
  { id: "tr04", family: "country_starts_with_letter", letter: "İ", difficulty: "easy",
    prompt: "İ harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "İtalya", "İran", "İrlanda", "İspanya", "İsrail", "İsveç",
      "İsviçre", "İzlanda",
    ] },
  { id: "tr05", family: "country_starts_with_letter", letter: "K", difficulty: "easy",
    prompt: "K harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Kanada", "Katar", "Kazakistan", "Kenya", "Kıbrıs", "Kolombiya",
      "Kosova", "Küba", "Kuveyt", "Kırgızistan", "Kuzey Kore", "Kamerun",
      "Kamboçya", "Komorlar", "Karadağ", "Kongo", "Kuzey Makedonya",
      "Kore", "Kap Verde", "Kiribati",
    ] },
  { id: "tr06", family: "country_starts_with_letter", letter: "G", difficulty: "medium",
    prompt: "G harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Gürcistan", "Gana", "Guatemala", "Gine", "Gabon", "Gambiya",
      "Grenada", "Guyana",
    ] },
  { id: "tr07", family: "country_starts_with_letter", letter: "M", difficulty: "easy",
    prompt: "M harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Mısır", "Meksika", "Macaristan", "Malezya", "Moğolistan", "Monako",
      "Mozambik", "Madagaskar", "Mali", "Malta", "Mauritius", "Moritanya",
      "Malavi", "Maldivler", "Makedonya",
    ] },
  { id: "tr08", family: "country_starts_with_letter", letter: "P", difficulty: "medium",
    prompt: "P harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Portekiz", "Peru", "Pakistan", "Panama", "Paraguay", "Polonya",
      "Papua Yeni Gine", "Palau",
    ] },
  { id: "tr09", family: "country_starts_with_letter", letter: "S", difficulty: "easy",
    prompt: "S harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Suriye", "Suudi Arabistan", "Sudan", "Senegal", "Sırbistan",
      "Slovenya", "Slovakya", "Somali", "Sri Lanka", "Singapur", "Seyşeller",
      "Surinam",
    ] },
  { id: "tr10", family: "country_starts_with_letter", letter: "D", difficulty: "medium",
    prompt: "D harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Danimarka", "Dominik Cumhuriyeti", "Dominika",
    ] },
  { id: "tr11", family: "country_starts_with_letter", letter: "H", difficulty: "medium",
    prompt: "H harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Hindistan", "Hollanda", "Hırvatistan", "Honduras", "Haiti",
    ] },
  { id: "tr12", family: "country_starts_with_letter", letter: "T", difficulty: "easy",
    prompt: "T harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Türkiye", "Tayland", "Tayvan", "Tunus", "Türkmenistan", "Tacikistan",
      "Tanzanya", "Togo", "Tonga", "Trinidad", "Tuvalu",
    ] },
  { id: "tr13", family: "country_starts_with_letter", letter: "L", difficulty: "medium",
    prompt: "L harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Letonya", "Litvanya", "Lübnan", "Libya", "Liberya", "Lihtenştayn",
      "Liechtenstein", "Lüksemburg", "Laos", "Lesotho",
    ] },
  { id: "tr14", family: "country_starts_with_letter", letter: "N", difficulty: "medium",
    prompt: "N harfiyle başlayan bir ülke yaz.",
    acceptedAnswers: [
      "Norveç", "Nepal", "Nikaragua", "Nijerya", "Nijer", "Niger",
      "Namibya", "Nauru",
    ] },

  // ── country by criteria (region / coast / feature) ───────────────────────
  { id: "tr15", family: "country_by_criteria", difficulty: "easy",
    prompt: "Avrupa'da yer alan bir ülke yaz.",
    acceptedAnswers: [
      "Almanya", "Fransa", "İspanya", "İtalya", "İngiltere", "Yunanistan",
      "Portekiz", "Belçika", "Hollanda", "İsveç", "Norveç", "Finlandiya",
      "Polonya", "Avusturya", "İsviçre", "Macaristan", "Çekya", "Romanya",
      "Bulgaristan", "Hırvatistan", "Sırbistan", "Slovenya", "Slovakya",
      "Danimarka", "İrlanda", "İzlanda", "Estonya", "Letonya", "Litvanya",
      "Türkiye", "Arnavutluk", "Bosna Hersek", "Kosova", "Kuzey Makedonya",
      "Karadağ", "Lüksemburg", "Malta", "Kıbrıs",
    ] },
  { id: "tr16", family: "country_by_criteria", difficulty: "easy",
    prompt: "Güney Amerika'da yer alan bir ülke yaz.",
    acceptedAnswers: [
      "Brezilya", "Arjantin", "Şili", "Peru", "Kolombiya", "Venezuela",
      "Uruguay", "Paraguay", "Ekvador", "Bolivya", "Guyana", "Surinam",
    ] },
  { id: "tr17", family: "country_by_criteria", difficulty: "easy",
    prompt: "Afrika'da yer alan bir ülke yaz.",
    acceptedAnswers: [
      "Mısır", "Fas", "Cezayir", "Tunus", "Libya", "Sudan", "Etiyopya",
      "Kenya", "Nijerya", "Gana", "Senegal", "Mali", "Güney Afrika",
      "Angola", "Kongo", "Kamerun", "Uganda", "Tanzanya", "Zimbabve",
      "Mozambik", "Botsvana", "Namibya", "Madagaskar", "Ruanda", "Fildişi Sahili",
      "Çad", "Nijer", "Niger", "Somali", "Eritre", "Cibuti", "Gambiya",
      "Togo", "Benin", "Liberya", "Sierra Leone", "Malavi", "Zambia",
      "Lesotho", "Eswatini", "Svaziland", "Burundi", "Komoro", "Gabon",
      "Ekvator Ginesi", "Gine", "Gine-Bissau", "Güney Sudan",
    ] },
  { id: "tr18", family: "country_by_criteria", difficulty: "easy",
    prompt: "Asya'da yer alan bir ülke yaz.",
    acceptedAnswers: [
      "Japonya", "Çin", "Hindistan", "Türkiye", "İran", "Irak", "Suudi Arabistan",
      "Tayland", "Vietnam", "Endonezya", "Malezya", "Pakistan", "Afganistan",
      "Kazakistan", "Özbekistan", "Azerbaycan", "Gürcistan", "Ermenistan",
      "Filipinler", "Moğolistan", "Kuzey Kore", "Güney Kore", "Myanmar",
      "Kamboçya", "Laos", "Nepal", "Butan", "Bangladeş", "Sri Lanka",
      "Katar", "Bahreyn", "Kuveyt", "BAE", "Umman", "Yemen", "Ürdün",
      "Lübnan", "İsrail", "Suriye", "Singapur", "Tayvan",
    ] },
  { id: "tr19", family: "country_by_criteria", difficulty: "medium",
    prompt: "Kuzey Amerika'da yer alan bir ülke yaz.",
    acceptedAnswers: [
      "ABD", "Amerika", "Kanada", "Meksika", "Guatemala", "Küba", "Panama",
      "Kosta Rika", "Honduras", "Nikaragua", "El Salvador", "Belize",
      "Jamaika", "Haiti", "Dominik Cumhuriyeti", "Bahamas",
    ] },
  { id: "tr20", family: "country_by_criteria", difficulty: "easy",
    prompt: "Denize kıyısı olmayan bir ülke yaz.",
    acceptedAnswers: [
      "İsviçre", "Avusturya", "Macaristan", "Çekya", "Slovakya", "Sırbistan",
      "Kosova", "Kuzey Makedonya", "Kazakistan", "Afganistan", "Moğolistan",
      "Nepal", "Bolivya", "Paraguay", "Ruanda", "Uganda", "Etiyopya",
      "Mali", "Niger", "Nijer", "Lüksemburg", "Andorra", "Çad", "Malavi",
      "Zimbabve", "Botsvana", "Lesotho", "Eswatini", "Svaziland", "Zambia",
      "Burundi", "Kırgızistan", "Tacikistan", "Türkmenistan", "Özbekistan",
    ] },
  { id: "tr21", family: "country_by_criteria", difficulty: "medium",
    prompt: "Akdeniz'e kıyısı olan bir ülke yaz.",
    acceptedAnswers: [
      "Türkiye", "Yunanistan", "İtalya", "Fransa", "İspanya", "Fas",
      "Cezayir", "Tunus", "Libya", "Mısır", "Lübnan", "İsrail", "Suriye",
      "Kıbrıs", "Malta", "Hırvatistan", "Arnavutluk", "Karadağ",
    ] },
  { id: "tr22", family: "country_by_criteria", difficulty: "medium",
    prompt: "Karadeniz'e kıyısı olan bir ülke yaz.",
    acceptedAnswers: [
      "Türkiye", "Bulgaristan", "Romanya", "Ukrayna", "Rusya", "Gürcistan",
    ] },
  { id: "tr23", family: "country_by_criteria", difficulty: "easy",
    prompt: "Orta Doğu'da yer alan bir ülke yaz.",
    acceptedAnswers: [
      "Türkiye", "İran", "Irak", "Suriye", "Lübnan", "İsrail", "Ürdün",
      "Suudi Arabistan", "Katar", "Bahreyn", "Kuveyt", "BAE", "Umman", "Yemen",
      "Filistin",
    ] },
  { id: "tr24", family: "country_by_criteria", difficulty: "medium",
    prompt: "Atlas Okyanusu'na kıyısı olan bir ülke yaz.",
    acceptedAnswers: [
      "Portekiz", "İspanya", "Fransa", "İrlanda", "İngiltere", "Birleşik Krallık",
      "Norveç", "İzlanda", "ABD", "Amerika", "Kanada", "Brezilya", "Arjantin",
      "Uruguay", "Fas", "Senegal", "Gana", "Nijerya", "Angola", "Namibya",
      "Güney Afrika", "Mauritania", "Moritanya", "Fildişi Sahili",
    ] },
  { id: "tr25", family: "country_by_criteria", difficulty: "medium",
    prompt: "Binlerce adadan ya da bir takımadadan oluşan bir ülke yaz.",
    acceptedAnswers: [
      "Japonya", "Endonezya", "Filipinler", "İngiltere", "Birleşik Krallık",
      "İrlanda", "İzlanda", "Yeni Zelanda", "Malta", "Kıbrıs", "Maldivler",
      "Madagaskar", "Sri Lanka", "Küba", "Bahamas", "Jamaika", "Seyşeller",
      "Komorlar", "Tonga", "Fiji", "Mauritius",
    ] },
  { id: "tr26", family: "country_by_criteria", difficulty: "easy",
    prompt: "Türkiye'ye komşu olan bir ülke yaz.",
    acceptedAnswers: [
      "Yunanistan", "Bulgaristan", "Gürcistan", "Ermenistan", "İran",
      "Irak", "Suriye", "Nahçıvan", "Azerbaycan",
    ] },
  { id: "tr27", family: "country_by_criteria", difficulty: "medium",
    prompt: "Ekvator'un içinden geçtiği bir ülke yaz.",
    acceptedAnswers: [
      "Ekvador", "Kolombiya", "Brezilya", "Kenya", "Uganda", "Endonezya",
      "Gabon", "Kongo", "Somali", "Sao Tome", "Maldivler",
    ] },
];

// ─────────────────────────────────────────────────────────────────────────────
// Flag guess — flag emoji → country name (curated, widely recognised subset)
//   Feeds BOTH the write `flag_to_country_text` family and the planner's
//   generated `flag_to_country_mc` family.  Kept deliberately small so direct
//   flag→country never dominates the multiple-choice pool.
// ─────────────────────────────────────────────────────────────────────────────

export interface FlagGuessBankEntry {
  id:               string;
  /** Flag emoji (composed regional indicator pair). */
  flag:             string;
  difficulty:       ConquestQuestionDifficulty;
  acceptedAnswers:  string[];
}

export const CONQUEST_FLAG_GUESS_BANK: FlagGuessBankEntry[] = [
  { id: "fg01", flag: "🇯🇵", difficulty: "easy",   acceptedAnswers: ["Japonya", "Japan"] },
  { id: "fg02", flag: "🇧🇷", difficulty: "easy",   acceptedAnswers: ["Brezilya", "Brazil"] },
  { id: "fg03", flag: "🇩🇪", difficulty: "easy",   acceptedAnswers: ["Almanya", "Germany"] },
  { id: "fg04", flag: "🇫🇷", difficulty: "easy",   acceptedAnswers: ["Fransa", "France"] },
  { id: "fg05", flag: "🇮🇹", difficulty: "easy",   acceptedAnswers: ["İtalya", "Italya", "Italy"] },
  { id: "fg06", flag: "🇪🇸", difficulty: "easy",   acceptedAnswers: ["İspanya", "Ispanya", "Spain"] },
  { id: "fg07", flag: "🇬🇧", difficulty: "easy",   acceptedAnswers: ["İngiltere", "Ingiltere", "Birleşik Krallık", "UK", "Britanya"] },
  { id: "fg08", flag: "🇺🇸", difficulty: "easy",   acceptedAnswers: ["ABD", "Amerika", "Amerika Birleşik Devletleri", "USA", "United States"] },
  { id: "fg09", flag: "🇨🇦", difficulty: "easy",   acceptedAnswers: ["Kanada", "Canada"] },
  { id: "fg10", flag: "🇨🇳", difficulty: "easy",   acceptedAnswers: ["Çin", "Cin", "China"] },
  { id: "fg11", flag: "🇷🇺", difficulty: "easy",   acceptedAnswers: ["Rusya", "Russia"] },
  { id: "fg12", flag: "🇰🇷", difficulty: "medium", acceptedAnswers: ["Güney Kore", "Guney Kore", "Kore", "South Korea", "Korea"] },
  { id: "fg13", flag: "🇲🇽", difficulty: "easy",   acceptedAnswers: ["Meksika", "Mexico"] },
  { id: "fg14", flag: "🇦🇷", difficulty: "medium", acceptedAnswers: ["Arjantin", "Argentina"] },
  { id: "fg15", flag: "🇦🇺", difficulty: "easy",   acceptedAnswers: ["Avustralya", "Australia"] },
  { id: "fg16", flag: "🇪🇬", difficulty: "medium", acceptedAnswers: ["Mısır", "Misir", "Egypt"] },
  { id: "fg17", flag: "🇹🇷", difficulty: "easy",   acceptedAnswers: ["Türkiye", "Turkiye", "Turkey"] },
  { id: "fg18", flag: "🇬🇷", difficulty: "easy",   acceptedAnswers: ["Yunanistan", "Greece"] },
  { id: "fg19", flag: "🇳🇱", difficulty: "easy", acceptedAnswers: ["Hollanda", "Netherlands"] },
  { id: "fg20", flag: "🇵🇹", difficulty: "easy", acceptedAnswers: ["Portekiz", "Portugal"] },
  { id: "fg21", flag: "🇸🇪", difficulty: "easy", acceptedAnswers: ["İsveç", "Isveç", "Sweden"] },
  { id: "fg22", flag: "🇨🇭", difficulty: "medium", acceptedAnswers: ["İsviçre", "Isviçre", "Switzerland"] },
  { id: "fg23", flag: "🇮🇳", difficulty: "easy",   acceptedAnswers: ["Hindistan", "India"] },
  { id: "fg24", flag: "🇵🇱", difficulty: "easy", acceptedAnswers: ["Polonya", "Poland"] },
  { id: "fg25", flag: "🇳🇴", difficulty: "easy", acceptedAnswers: ["Norveç", "Norway"] },
  { id: "fg26", flag: "🇿🇦", difficulty: "medium", acceptedAnswers: ["Güney Afrika", "Guney Afrika", "South Africa"] },
  { id: "fg27", flag: "🇸🇦", difficulty: "medium", acceptedAnswers: ["Suudi Arabistan", "Saudi Arabia", "Suudi"] },
  { id: "fg28", flag: "🇮🇷", difficulty: "medium", acceptedAnswers: ["İran", "Iran"] },
];

// ─────────────────────────────────────────────────────────────────────────────
// Picker helpers (legacy live picker — see conquestChallenges.ts)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Pick a random quiz entry that has not yet been used in this match.
 * Falls back to the full pool only when every quiz question has been shown.
 */
export function pickQuizBankEntry(usedIds: string[] = []): { entry: QuizBankEntry; id: string } {
  const available = CONQUEST_QUIZ_BANK.filter(e => !usedIds.includes(e.id));
  const pool = available.length > 0 ? available : CONQUEST_QUIZ_BANK;
  const entry = pool[Math.floor(Math.random() * pool.length)];
  return { entry, id: entry.id };
}

/**
 * Pick a random type-race entry, preferring unused ones.
 */
export function pickTypeRaceBankEntry(usedIds: string[] = []): { entry: TypeRaceBankEntry; id: string } {
  const available = CONQUEST_TYPE_RACE_BANK.filter(e => !usedIds.includes(e.id));
  const pool = available.length > 0 ? available : CONQUEST_TYPE_RACE_BANK;
  const entry = pool[Math.floor(Math.random() * pool.length)];
  return { entry, id: entry.id };
}

/**
 * Pick a random flag-guess entry, preferring unused ones.
 */
export function pickFlagGuessBankEntry(usedIds: string[] = []): { entry: FlagGuessBankEntry; id: string } {
  const available = CONQUEST_FLAG_GUESS_BANK.filter(e => !usedIds.includes(e.id));
  const pool = available.length > 0 ? available : CONQUEST_FLAG_GUESS_BANK;
  const entry = pool[Math.floor(Math.random() * pool.length)];
  return { entry, id: entry.id };
}
