import assert from 'node:assert/strict';
import { before, test } from 'node:test';
import { initializePhysics } from '../physics';
import { NET } from '../../../../shared/party-lab/network/protocol';
import { MODE_SELECTIONS } from '../../../../shared/party-lab/modes';
import { CAR, IDLE, RACE, steeringRate, type DriveInput } from './config';
import { RaceTrack, crossedGate } from './track';
import { RaceGame } from './game';
import { advance, missedCheckpoint, newProgress, raceDistance, raceOrder, wrongWay } from './rules';
import { VIEWS, newCamera, updateCamera } from './camera';
before(initializePhysics);
test('simpler circuit has five readable corners, long straights and a similar lap length',()=>{
  const t=new RaceTrack(),corners=t.sections.filter(s=>s.radius>0),straights=t.sections.filter(s=>s.radius===0);
  assert.ok(t.length>=550&&t.length<=620);assert.equal(corners.length,5);
  assert.ok(corners.every(s=>s.turn<=Math.PI/2+.001));assert.equal(corners.filter(s=>s.radius<30).length,1);
  assert.ok(straights[0].length+straights[straights.length-1].length>125);
  assert.ok(straights.filter(s=>s.length>60).length>=4);
  assert.ok(t.points.every(p=>p.width>=10&&p.width<=12&&Number.isFinite(p.curve)));
  assert.ok(straights.slice(0,-1).every(s=>t.at(s.start+s.length/2).curve<.00001));
  for(let i=0;i<t.checkpoints.length;i++){const p=t.checkpoints[i];assert.ok(Math.abs(p.s-i*t.length/t.checkpoints.length)<.001);assert.ok(t.project(p).distance<.001);}
  assert.ok(t.barriers.length<350);assert.ok(t.risk(t.length*.48));
});
const run=(g:RaceGame,seconds:number,input:DriveInput=IDLE)=>{for(let i=0;i<Math.round(seconds/RACE.step);i++)g.step(input);};
const gateCross=(track:RaceTrack,n:number,backward=false)=>{const p=track.checkpoints[n],a={x:p.x-p.tx,y:.64,z:p.z-p.tz},b={x:p.x+p.tx,y:.64,z:p.z+p.tz};return backward?[b,a]:[a,b];};
function fixture(){const g=new RaceGame(2);g.phase='racing';g.bots=false;g.cars[0].place({x:0,y:.64,z:36},0);g.cars[1].place(g.track.pose(160),0);run(g,.2);return g;}

test('local-only identity and protocol 12 stay outside online/mixed selection',()=>{assert.equal(NET.version,12);assert.ok(!MODE_SELECTIONS.some(m=>String(m)===RACE.id));assert.throws(()=>new RaceGame(4 as 2));});
test('grid has separate equal front row and staggered third seat',()=>{for(const count of [2,3]as const){const g=new RaceGame(count);try{for(let a=0;a<count;a++)for(let b=a+1;b<count;b++){const p=g.cars[a].body.translation(),q=g.cars[b].body.translation();assert.ok(Math.hypot(p.x-q.x,p.z-q.z)>3.9);}assert.equal(g.world.bodies.len(),count);assert.ok(g.cars.every(c=>c.body.isCcdEnabled()));}finally{g.dispose();}}});
test('countdown ignores throttle, brake, steering and reset',()=>{const g=new RaceGame(3);try{const starts=g.cars.map(c=>c.body.translation());run(g,2.8,{throttle:1,brake:1,steer:1,reset:true});assert.equal(g.phase,'countdown');g.cars.forEach((c,i)=>{assert.ok(Math.hypot(c.body.translation().x-starts[i].x,c.body.translation().z-starts[i].z)<.01);assert.equal(g.progress[i].resets,0);});run(g,.3);assert.equal(g.phase,'racing');}finally{g.dispose();}});
test('ordered gates arm the start, count exactly three complete laps and finish once',()=>{const t=new RaceTrack(),p=newProgress();let time=0;for(let lap=0;lap<=3;lap++)for(let i=0;i<18;i++){if(lap===3&&i>0)break;const [a,b]=gateCross(t,i);assert.ok(advance(p,t,a,b,++time));assert.equal(p.laps,lap);}assert.equal(p.laps,3);assert.equal(p.finish,55);const [a,b]=gateCross(t,1);assert.equal(advance(p,t,a,b,56),false);});
test('skipping a gate, interior cutting and finish spam cannot advance',()=>{const t=new RaceTrack(),p=newProgress();const [a,b]=gateCross(t,0);advance(p,t,a,b,0);for(const n of [2,5,8,17,0,0]){const [x,y]=gateCross(t,n);assert.equal(advance(p,t,x,y,1),false);}assert.equal(p.next,1);assert.equal(p.laps,0);const gate=t.checkpoints[1],outside={x:gate.x+gate.tz*25,y:.64,z:gate.z-gate.tx*25};assert.equal(advance(p,t,{x:outside.x-gate.tx,y:.64,z:outside.z-gate.tz},{x:outside.x+gate.tx,y:.64,z:outside.z+gate.tz},2),false);});
test('backward finish, reversing across next gate and airborne/void crossing fail',()=>{const t=new RaceTrack(),p=newProgress();for(const n of [0,1]){p.next=n;const [a,b]=gateCross(t,n,true);assert.equal(advance(p,t,a,b,2),false);}const [a,b]=gateCross(t,0);assert.equal(crossedGate({...a,y:4},{...b,y:4},t.checkpoints[0]),false);assert.equal(crossedGate({...a,y:-3},{...b,y:-3},t.checkpoints[0]),false);});
test('swept gates detect a full max-speed physics step, independent of render FPS',()=>{const t=new RaceTrack(),g=t.checkpoints[2];for(const speed of [90,110,130,150]){const d=speed/3.6/60;assert.ok(crossedGate({x:g.x-g.tx*d*.4,y:.64,z:g.z-g.tz*d*.4},{x:g.x+g.tx*d*.6,y:.64,z:g.z+g.tz*d*.6},g));}});
test('wrong-way dwell ignores spins and short reverse recovery; clears with hysteresis',()=>{const p=newProgress();for(let i=0;i<80;i++)wrongWay(p,-10,1/60);assert.equal(p.wrong,false);for(let i=0;i<60;i++)wrongWay(p,4,1/60);assert.equal(p.wrong,false);for(let i=0;i<130;i++)wrongWay(p,-10,1/60);assert.equal(p.wrong,true);for(let i=0;i<30;i++)wrongWay(p,10,1/60);assert.equal(p.wrong,true);for(let i=0;i<11;i++)wrongWay(p,10,1/60);assert.equal(p.wrong,false);});
test('order uses lap then ordered sector and clamped segment progress',()=>{const t=new RaceTrack(),p=[newProgress(),newProgress(),newProgress()];p.forEach(x=>{x.started=true;x.next=4;});p[0].laps=1;p[2].next=5;assert.deepEqual(raceOrder(p,t,[110,120,140]),[0,2,1]);const before=raceDistance(p[1],t,120),cut=raceDistance(p[1],t,t.length*.7);assert.ok(cut<=4*t.length/18);assert.ok(before>0);const reset=[{...newProgress(),started:true,laps:1,next:1},{...newProgress(),started:true,laps:0,next:0}];assert.deepEqual(raceOrder(reset,t,[t.length-2,t.length-1]),[0,1]);p[1].finish=80;p[2].finish=79;p[0].finish=82;assert.deepEqual(raceOrder(p,t,[1,2,3]),[2,1,0]);});
test('fall resets only to last valid gate, preserves all progress and applies hold/cooldown',()=>{const g=fixture();try{const p=g.progress[0];p.started=true;p.next=6;p.laps=1;g.cars[0].body.setTranslation({x:70,y:-4,z:60},true);g.step();assert.equal(p.resets,1);assert.equal(p.laps,1);assert.equal(p.next,6);assert.ok(p.hold>1);assert.equal(g.cars[0].speed,0);const at=g.cars[0].body.translation();run(g,.7,{...IDLE,throttle:1,reset:true});assert.equal(p.resets,1);assert.ok(Math.hypot(g.cars[0].body.translation().x-at.x,g.cars[0].body.translation().z-at.z)<.01);assert.equal(p.next,6);}finally{g.dispose();}});
test('stationary off-road and inverted chassis recover with same reset rules',()=>{for(const upside of [false,true]){const g=fixture();try{const c=g.cars[0];c.place(g.track.pose(150,10),0);if(upside)c.body.setRotation({x:1,y:0,z:0,w:0},true);run(g,4.5);assert.ok(g.progress[0].resets>=1);assert.equal(g.progress[0].laps,0);}finally{g.dispose();}}});
test('manual reset is edge triggered and cannot jump to unearned sectors',()=>{const g=fixture();try{g.progress[0].started=true;g.progress[0].next=2;g.cars[0].place(g.track.pose(300),0);run(g,6,{...IDLE,reset:true});assert.equal(g.progress[0].resets,1);assert.equal(g.progress[0].next,2);}finally{g.dispose();}});
test('missed gate warning distinguishes upcoming gates and never awards a cut',()=>{const t=new RaceTrack(),p=newProgress();p.started=true;p.next=5;const s=t.checkpoints[5].s;assert.equal(missedCheckpoint(p,t,s-3),false);assert.equal(missedCheckpoint(p,t,s+3),true);assert.equal(p.next,5);p.hold=1;assert.equal(missedCheckpoint(p,t,s+3),false);});
test('bot physically backtracks to a missed gate and completes all laps without reset',()=>{const g=new RaceGame(3);try{g.autoHuman=true;while(g.time<15)g.step();const c=g.cars[1],p=g.progress[1],gate=g.track.checkpoints[p.next],expected=p.next;c.place(g.track.pose(gate.s+3,7),Math.atan2(gate.tx,gate.tz));g.step();assert.equal(p.next,expected);assert.equal(g.drivers[1].recovering,expected);while(g.phase!=='results')g.step();assert.equal(p.laps,3);assert.ok(p.finish!==null);assert.equal(p.resets,0);assert.equal(g.invalid,0);}finally{g.dispose();}});
test('asphalt has more acceleration and lateral grip; S brakes before reversing',()=>{const asphalt=fixture(),grass=fixture();try{grass.cars[0].place({x:-7,y:.64,z:36},0);run(asphalt,1,{...IDLE,throttle:1});run(grass,1,{...IDLE,throttle:1});assert.ok(asphalt.cars[0].speed>grass.cars[0].speed*1.7);assert.ok(grass.cars[0].grass);asphalt.cars[0].body.setLinvel({x:0,y:0,z:20},true);run(asphalt,.5,{...IDLE,brake:1});assert.ok(asphalt.cars[0].forwardSpeed>9);run(asphalt,1.8,{...IDLE,brake:1});assert.ok(asphalt.cars[0].forwardSpeed< -2);assert.ok(asphalt.cars[0].forwardSpeed>= -CAR.reverse-.1);assert.ok(steeringRate(8)>steeringRate(25));}finally{asphalt.dispose();grass.dispose();}});
test('real head-on contact slows both cars without invalid bodies or giant rotation',()=>{const g=fixture();try{const [a,b]=g.cars;a.place({x:0,y:.64,z:32},0);b.place({x:0,y:.64,z:44},Math.PI);a.body.setLinvel({x:0,y:0,z:24},true);b.body.setLinvel({x:0,y:0,z:-20},true);run(g,.5);assert.ok(g.contacts>0);assert.ok(a.speed<10&&b.speed<10);assert.equal(g.invalid,0);assert.ok(Math.abs(a.body.angvel().y)<=3);}finally{g.dispose();}});
test('physical 90/110/150 km/h barrier impacts cannot tunnel through its outer face',()=>{for(const speed of [90,110,150]){const g=fixture();try{const c=g.cars[0],p=g.track.at(15);c.place(g.track.pose(15,p.width/2-1.5),Math.atan2(p.tz,-p.tx));c.body.setLinvel({x:p.tz*speed/3.6,y:0,z:-p.tx*speed/3.6},true);let far=0;for(let i=0;i<60;i++){g.step();far=Math.max(far,c.projection.distance);}assert.ok(g.contacts>0);assert.ok(far<8.2,`${speed} km/h: ${far} m`);assert.equal(g.invalid,0);}finally{g.dispose();}}});
test('physical skipped-gate, backwards finish and driven infield cuts do not earn progress',()=>{
  const g=fixture();try{const c=g.cars[0],p=g.progress[0];p.started=true;p.next=1;let q=g.track.checkpoints[2];c.place(g.track.pose(q.s-2),Math.atan2(q.tx,q.tz));c.body.setLinvel({x:q.tx*25,y:0,z:q.tz*25},true);run(g,.3);assert.equal(p.next,1);
    p.next=0;q=g.track.checkpoints[0];c.place(g.track.pose(2),Math.atan2(q.tx,q.tz)+Math.PI);c.body.setLinvel({x:-q.tx*20,y:0,z:-q.tz*20},true);run(g,.3);assert.equal(p.next,0);assert.equal(p.laps,0);
    p.next=2;c.place({x:12,y:.64,z:60},Math.PI/2);run(g,5,{...IDLE,throttle:1});assert.ok(c.body.translation().x>40);assert.equal(p.next,2);assert.equal(p.laps,0);
  }finally{g.dispose();}
});
test('full throttle reaches but cannot engine-accelerate above race-specific top speed',()=>{const g=new RaceGame(2,{scale:5,width:100});try{g.phase='racing';g.bots=false;g.cars[0].place(g.track.pose(80),0);run(g,5,{...IDLE,throttle:1});assert.ok(g.cars[0].speed>CAR.maxSpeed-.5);assert.ok(g.cars[0].speed<CAR.maxSpeed+.1);}finally{g.dispose();}});
test('all four camera views remain world-up and pull in at solid scenery',()=>{const g=fixture();try{for(let i=0;i<VIEWS.length;i++){const c=newCamera();updateCamera(c,g.world,{x:0,y:.64,z:36},0,20,1/60,i);assert.ok(c.position.y>1);assert.ok(c.fov>=58);}const c=newCamera();updateCamera(c,g.world,{x:-10,y:.64,z:40},Math.PI/2,0,1/60,3);assert.ok(c.boom<VIEWS[3].distance);assert.ok(c.position.x>-12);}finally{g.dispose();}});
test('handbrake duration trades speed for bounded rotation and lateral slip',()=>{
  const results=[0,.1,.4,1.5].map(hold=>{const g=new RaceGame(2,{width:150});try{g.phase='racing';g.bots=false;const c=g.cars[0],p=g.track.at(205),h=Math.atan2(p.tx,p.tz);g.cars[1].place(g.track.pose(400),0);c.place(g.track.pose(205),h);c.body.setLinvel({x:p.tx*65/3.6,y:0,z:p.tz*65/3.6},true);let slip=0;for(let i=0;i<90;i++){g.step({...IDLE,steer:.5,handbrake:i<hold*60});const v=c.body.linvel();slip=Math.max(slip,Math.abs(v.x*Math.cos(c.heading)-v.z*Math.sin(c.heading)));}assert.equal(g.invalid,0);assert.ok(Math.abs(c.body.angvel().y)<3);return {speed:c.speed,yaw:Math.abs(c.heading-h),slip};}finally{g.dispose();}});
  for(let i=1;i<results.length;i++){assert.ok(results[i].speed<results[i-1].speed);assert.ok(results[i].yaw>results[i-1].yaw);}
  assert.ok(results[1].yaw-results[0].yaw<.1);assert.ok(results[2].slip>results[0].slip*1.5);assert.ok(results[3].speed<results[0].speed*.3);
});
test('handbrake before, during and after a real side impact retains momentum without instability',()=>{
  for(const timing of [0,1,2]){const g=fixture();try{const [a,b]=g.cars;a.place({x:0,y:.64,z:40},0);b.place({x:-4,y:.64,z:41},.6);a.body.setLinvel({x:0,y:0,z:18},true);b.body.setLinvel({x:11,y:0,z:18},true);let impact=-1,displaced=0;for(let i=0;i<120;i++){g.step({...IDLE,steer:.25,handbrake:timing===0?i<15:timing===1?i<35:impact>=0&&i>impact&&i<impact+24});if(impact<0&&g.events.some(e=>e.kind==='impact'))impact=i;displaced=Math.max(displaced,Math.abs(a.body.translation().x));assert.ok(a.speed<40);}assert.ok(impact>=0);assert.ok(displaced>.5);assert.equal(g.invalid,0);}finally{g.dispose();}}
});
test('asphalt slip settles faster than grass while grass acceleration stays penalized',()=>{
  const g=fixture();try{const c=g.cars[0];c.body.setLinvel({x:4,y:0,z:15},true);run(g,.1);const road=Math.abs(c.body.linvel().x);c.place({x:-7,y:.64,z:36},0);c.body.setLinvel({x:4,y:0,z:15},true);run(g,.1);assert.ok(c.grass);assert.ok(Math.abs(c.body.linvel().x)>road*2);assert.ok(CAR.grip>CAR.grassGrip*4);}finally{g.dispose();}
});
test('2P and 3P bots run real complete three-lap races; rematch starts clean',()=>{for(const n of [2,3]as const){const g=new RaceGame(n);try{g.autoHuman=true;for(let i=0;i<9000&&g.phase!=='results';i++)g.step();assert.equal(g.phase,'results');assert.ok(g.progress.every(p=>p.finish!==null&&p.laps===3));assert.ok(g.time>75&&g.time<125,`${g.time}`);assert.equal(g.invalid,0);assert.ok(g.progress.every(p=>p.resets===0));}finally{g.dispose();}const fresh=new RaceGame(n);try{assert.equal(fresh.phase,'countdown');assert.equal(fresh.time,0);assert.ok(fresh.progress.every(p=>p.laps===0&&p.finish===null&&p.resets===0));assert.equal(fresh.world.bodies.len(),n);}finally{fresh.dispose();}}});
