import type {RaceGame,RaceSnapshot} from './game.js';
import type {Progress} from './rules.js';
import type {DriveInput} from './config.js';
export interface RaceWire {seats:number[];phase:RaceSnapshot['phase'];time:number;countdown:number;firstFinish:number|null;progress:Progress[];lapAt:number[];motion:number[][];held:number[];inputs:DriveInput[];contacts:number;enabled:boolean[];}
export function raceTransforms(g:RaceGame){const bytes=new Uint8Array(g.count*28),view=new DataView(bytes.buffer);g.cars.forEach((c,i)=>{const p=c.body.translation(),q=c.body.rotation();[p.x,p.y,p.z,q.x,q.y,q.z,q.w].forEach((n,j)=>view.setFloat32((i*7+j)*4,n,true));});return bytes;}
export function raceSection(g:RaceGame,seats:number[],held:number[],inputs:DriveInput[]):RaceWire{return{seats,phase:g.phase,time:g.time,countdown:g.countdown,firstFinish:g.firstFinish,progress:g.progress.map(p=>({...p})),lapAt:[...g.lapAt],held:[...held],inputs:inputs.map(i=>({...i})),contacts:g.contacts,enabled:g.cars.map(c=>c.body.isEnabled()),motion:g.cars.map(c=>{const v=c.body.linvel(),w=c.body.angvel();return[v.x,v.y,v.z,w.x,w.y,w.z,c.heading,c.steer,c.handbrake,+c.grounded,+c.grass];})};}
export function restoreRace(g:RaceGame,w:RaceWire,poses:ArrayLike<number>){g.phase=w.phase;g.time=w.time;g.countdown=w.countdown;g.firstFinish=w.firstFinish;g.contacts=w.contacts;g.events=[];
 g.cars.forEach((c,i)=>{const o=i*7,a=w.motion[i];c.body.setEnabled(w.enabled[i]);c.body.setTranslation({x:poses[o],y:poses[o+1],z:poses[o+2]},true);c.body.setRotation({x:poses[o+3],y:poses[o+4],z:poses[o+5],w:poses[o+6]},true);c.body.setLinvel({x:a[0],y:a[1],z:a[2]},true);c.body.setAngvel({x:a[3],y:a[4],z:a[5]},true);Object.assign(c,{heading:a[6],steer:a[7],handbrake:a[8],grounded:!!a[9],grass:!!a[10]});c.previous=c.body.translation();c.previousHeading=c.heading;c.projection=g.track.project(c.previous);Object.assign(g.progress[i],w.progress[i]);g.lapAt[i]=w.lapAt[i];});g.world.propagateModifiedBodyPositionsToColliders();
}
