/**
 * Designs Renk Kaosu's colour layout banks and writes
 * shared/party-lab/simulation/colors/layoutBank.ts. Deterministic: the same seeds give
 * the same file on every machine. Run: npx tsx scripts/build-party-lab-color-layouts.ts
 *
 * Each bank takes consecutive seeds, keeps a design only if it passes every
 * LAYOUT_RULE (and, for openings, maps the spawns onto each other), and drops designs
 * that equal an earlier one under a symmetry of the field plus a colour permutation.
 * Shrink stages 1–6 (73 … 7 tiles) get their own free layouts, checked with that stage's
 * rules (and reach from the ring it has just dropped); a small stage may have fewer
 * distinct designs than asked for (the seven-tile finale has exactly one).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { COLOR_SYMMETRIES, COLOR_TILE_COUNT } from "../shared/party-lab/maps/colors";
import {
  checkLayout,
  designLayout,
  encodeLayout,
  LAYOUT_STAGE_COUNT,
  NO_COLOR,
  spawnsEquivalent,
  type ColorLayout,
} from "../shared/party-lab/simulation/colors/layouts";
import { STAGE_SIZES } from "../shared/party-lab/simulation/colors/shrink";

const PERMUTATIONS: number[][] = [];
(function permute(prefix: number[], rest: number[]) {
  if (!rest.length) PERMUTATIONS.push(prefix);
  rest.forEach((c, i) => permute([...prefix, c], [...rest.slice(0, i), ...rest.slice(i + 1)]));
})([], [0, 1, 2, 3]);

/** Smallest encoding over the 12 symmetries × 24 colour permutations. */
function canonical(layout: ColorLayout) {
  let best = "";
  const moved = new Uint8Array(COLOR_TILE_COUNT);
  for (const map of COLOR_SYMMETRIES)
    for (const p of PERMUTATIONS) {
      for (let id = 0; id < COLOR_TILE_COUNT; id++) moved[map[id]] = layout[id] === NO_COLOR ? NO_COLOR : p[layout[id]];
      const code = encodeLayout(moved);
      if (!best || code < best) best = code;
    }
  return best;
}

function bank(count: number, order: 1 | 2 | 3, base: number, stage = 0, tries = 500) {
  const out: { seed: number; code: string }[] = [],
    seen = new Set<string>();
  for (let seed = base; out.length < count; seed++) {
    if (seed - base > tries) {
      if (stage > 0 && out.length) break;
      throw new Error(`bank ${order}/${stage}: not enough valid layouts`);
    }
    const layout = designLayout(seed, order, 24000, stage);
    if (!checkLayout(layout, stage).ok) continue;
    if (order !== 1 && !spawnsEquivalent(layout, order)) continue;
    const key = canonical(layout);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ seed, code: encodeLayout(layout) });
  }
  return out;
}

const cycle = bank(16, 1, 1000),
  three = bank(6, 3, 3000),
  two = bank(6, 2, 2000);
const stages = Array.from({ length: LAYOUT_STAGE_COUNT - 1 }, (_, k) => bank(8, 1, 4000 + 1000 * k, k + 1, 120));
const list = (entries: { seed: number; code: string }[], indent: string) =>
  entries.map(({ seed, code }) => `${indent}"${code}", // seed ${seed}`).join("\n");
const file = `// Generated by scripts/build-party-lab-color-layouts.ts — do not edit by hand.
// Renk Kaosu colour layouts: one character per tile id (0 blue, 1 yellow, 2 green, 3 pink, . none),
// designed by designLayout(seed, order) and checked against LAYOUT_RULES (layouts.ts).

/** Free layouts for every cycle after the first. */
export const CYCLE_LAYOUTS: readonly string[] = [
${list(cycle, "  ")}
];

/** First-cycle layouts: third-turn symmetric (3 players), half-turn symmetric (2 players). */
export const OPENING_LAYOUTS: Readonly<Record<2 | 3, readonly string[]>> = {
  3: [
${list(three, "    ")}
  ],
  2: [
${list(two, "    ")}
  ],
};

/** Shrink stages 1–6 (index 0–5): free layouts on the tiles each stage keeps ("." = gone). */
export const SHRINK_LAYOUTS: readonly (readonly string[])[] = [
${stages.map((entries, k) => `  // stage ${k + 1}: ${STAGE_SIZES[k + 1]} tiles\n  [\n${list(entries, "    ")}\n  ],`).join("\n")}
];
`;
const target = path.join(path.dirname(fileURLToPath(import.meta.url)), "../shared/party-lab/simulation/colors/layoutBank.ts");
fs.writeFileSync(target, file);
console.log(
  `wrote ${path.relative(process.cwd(), target)}: ${cycle.length} cycle, ${three.length} + ${two.length} opening, shrink ${stages.map((s) => s.length).join("/")} layouts`
);
